spring:
  application:
    name: once-backend

  datasource:
    url: jdbc:mysql://40.233.98.156:3306/once?sslMode=DISABLED&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
    username: jin
    password: rlawlsals2026016
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영은 validate 권장
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE