spring:
  application:
    name: once-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    #url: jdbc:mysql://localhost:3306/sharedcalendar?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    #username: root
    #password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영은 validate 권장
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


jwt:
  secret: your-jwt-secret-key-here-make-it-very-long-and-secure
  expiration: 604800 # 7 days in seconds